CREATE SCHEMA arp_mjpnatur_tmp;

CREATE TABLE arp_mjpnatur_tmp.flaechen (
    vereinbarungsart varchar NULL,
    vereinbarungid int4 NOT NULL,
    vbnr varchar(15) NOT NULL,
    pid int4 NULL,
    persid int4 NULL,
    bewirtschafter text NULL,
    flaechenart varchar(30) NULL,
    geometrie geometry(multipolygon, 2056) NULL,
    fallid int4 NULL,
    t_id int4 NOT NULL,
    flaechenid int4 NULL,
    flaechenartid int4 NULL,
    flaeche numeric(15, 5) NULL,
    gis_flaeche numeric NULL,
    legende int4 NULL,
    notiz text NULL,
    laufmeter numeric NULL,
    schnittzeitpunkt text NULL,
    flurname varchar NULL,
    oeqv_q_attest int2 NULL,
    oeqv_q_attest_txt varchar NULL,
    balkenmaeher bool NULL,
    herbstweide bool NULL,
    rkzugstreifen bool NULL,
    emden int2 NULL,
    emden_txt varchar NULL,
    bffii_flaeche numeric(15, 5) NULL,
    bffii_indikatoren varchar NULL,
    letzter_unterhalt date NULL,
    datum_beurt date NULL,
    datum_oeqv date NULL,
    gueltigab text NULL,
    gueltigbis timestamp NULL,
    wiesenkategorie int4 NULL,
    wiesenkat_txt varchar NULL,
    flaeche_hecke numeric(15, 5) NULL,
    besch_flaeche text NULL,
    besch_akarte text NULL,
    --
    vbart_bez text NULL,
    rrbbeschlussid int4 NULL,
    rrbnr text NULL,
    rrbdatum date NULL,
    --
    CONSTRAINT flaechen_pkey PRIMARY KEY (t_id)
);
